### ISSUE TITLE
Dependency Errors

### ISSUE THREAD

**Issue by peterjobrien** [freol35241/ltss#16]
Reporting two dependency errors I got when installing this from HACS:  geoalchemy2 and pyscopg2.
psycopg2 looks to be OS-related (FreeBSD 12), but I'm not sure what caused the failure of geoalchemy2.

I can see the manifest.json in custom_components/ltss on my machine with geoalchemy2 listed.
I was able to install geoalchemy2 with pip in the homeassistant venv which removed this error.

After a restart of homeassistant, I got an error that psycopg2 is missing but this I think is specific to FreeBSD.
On FreeBSD 12, I had to manually install py37-psycopg2 (using pkg) and then do pip install psycopg2.
This works even though I'm using python 3.8.
After another restart, I see the ltss hypertable in the database with populated rows and no errors on startup.

geoalchemy2 error:
```
Traceback (most recent call last):
  File "/usr/local/share/homeassistant/lib/python3.8/site-packages/homeassistant/loader.py", line 541, in _load_file
    module = importlib.import_module(path)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/homeassistant/homeassistant/custom_components/ltss/__init__.py", line 39, in <module>
    from .models import Base, LTSS
  File "/home/homeassistant/homeassistant/custom_components/ltss/models.py", line 16, in <module>
    from geoalchemy2 import Geometry
ModuleNotFoundError: No module named 'geoalchemy2'
```

System Info:
```
System Health

Home Assistant Core Integration

version: 0.118.4
installation_type: Home Assistant Core
dev: false
hassio: false
docker: false
virtualenv: true
python_version: 3.8.6
os_name: FreeBSD
os_version: 12.2-RC3
arch: amd64
timezone: America/Los_Angeles

Lovelace

dashboards: 1
mode: auto-gen
resources: 0
```

**Comment by mskorge** [comment]
I'm getting the same error for geoalchemy2 with the docker image and HACS-install. Installing it manually in the image with pip solves the problem until the container is upgraded/recreated.

**Comment by freol35241** [comment]
@peterjobrien @mskorge 
This (https://github.com/home-assistant/wheels-custom-integrations/pull/201) has now been merged and geoalchemy is part of the home-assistant-hosted wheels.

Could anyone (or both) of you test this with a fresh LTSS install from HACS and report back?

**Comment by mskorge** [comment]
@freol35241 thanks for looking in to this! 
I upgraded (redeployed) the docker container to version 0.118.5 but got the same error. I guess your PR will be in 1.0 when that gets out?

**Comment by freol35241** [comment]
@mskorge I am unsure to be honest. Haven't really got my head around how HACS (or Home Assistant? or both?) deals with custom components and their dependencies. But the PR is already merged and ```geoalchemy``` is now part of the hosted wheels (found here: https://wheels.home-assistant.io/) so my hope was that the error would be solved.

**Comment by freol35241** [comment]
Closing due to lack of activity

**Comment by ErgoPraxis** [comment]
Just tested it. Still an issue with LTSS 2.1.0 on HACS. The geoalchemy2 is missing.

**Comment by dgsardina** [comment]
@freol35241 Just having this issue on LTSS v2.1.1 on HACS. geoalchemy2 is missing. Doing ``pip install geoalchemy2`` fixes it until the container is regenerated.
