### ISSUE TITLE
Lot of "Error handling message: Unknown error" Messages since HA 0.109

### ISSUE THREAD

**Issue by CM000n** [freol35241/ltss#2]
Since HA version 0.109 I’m getting a lot of error messages which are probably caused by ltss:

`
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 20, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/frontend/__init__.py", line 550, in websocket_get_translations
    msg.get("config_flow"),
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 329, in async_get_translations
    resources = flatten(resource_func(results[0], components, category))
  File "/usr/src/homeassistant/homeassistant/helpers/translation.py", line 127, in merge_resources
    new_value = translation_strings[component].get(category)
KeyError: 'ltss'
`

Seems the error message is related to the current changes how translations are handled now in HA 0.109.

**Comment by freol35241** [comment]
Home assistant issue: home-assistant/core#34857

**Comment by freol35241** [comment]
@CM000n 

This seems to be fixed by home-assistant/core#35032 which should be in Home Assistant 109.3.
