### ISSUE TITLE
ValueError: A string literal cannot contain NUL (0x00) characters

### ISSUE THREAD

**Issue by st-schuler** [freol35241/ltss#216]
I get this error with HASS 2024.10 and 2024.11 and postgresql:

```python
Dieser Fehler wurde von einer benutzerdefinierten Integration verursacht

Logger: root
Quelle: custom_components/ltss/__init__.py:207
Integration: Long Time State Storage (LTSS) (Dokumentation)
Erstmals aufgetreten: 11:33:19 (1 Vorkommnisse)
Zuletzt protokolliert: 11:33:19

Uncaught thread exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1073, in _bootstrap_inner
    self.run()
  File "/config/custom_components/ltss/__init__.py", line 207, in run
    with session.begin():
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 147, in __exit__
    with util.safe_reraise():
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/util.py", line 145, in __exit__
    self.commit()
  File "<string>", line 2, in commit
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1302, in commit
    self._prepare_impl()
  File "<string>", line 2, in _prepare_impl
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 1277, in _prepare_impl
    self.session.flush()
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4341, in flush
    self._flush(objects)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4476, in _flush
    with util.safe_reraise():
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/util/langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/session.py", line 4437, in _flush
    flush_context.execute()
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 466, in execute
    rec.execute(self)
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/unitofwork.py", line 642, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 93, in save_obj
    _emit_insert_statements(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/orm/persistence.py", line 1048, in _emit_insert_statements
    result = connection.execute(
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1418, in execute
    return meth(
           ^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/sql/elements.py", line 515, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1640, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1846, in _execute_context
    return self._exec_single_context(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1986, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 2356, in _handle_dbapi_exception
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/base.py", line 1967, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.12/site-packages/sqlalchemy/engine/default.py", line 924, in do_execute
    cursor.execute(statement, parameters)
ValueError: A string literal cannot contain NUL (0x00) characters.
```

**Comment by michalk-k** [comment]
See this: https://github.com/freol35241/ltss/issues/213

BTW LTSS got blacklisted in HA due to this memory leak.
Unfortunately, I see no movement around development. Could be dead project :(

**Comment by Tupsi** [comment]
> See this: #213
> 
> BTW LTSS got blacklisted in HA due to this memory leak. Unfortunately, I see no movement around development. Could be dead project :(

does that mean, we have to find ourselfs something else to save long term statistics into a database?

**Comment by freol35241** [comment]
@st-schuler Please try out [v2.1.1-alpha](https://github.com/freol35241/ltss/releases/tag/v2.1.1-alpha). It should fix this error.

And for the blacklist, can you please point me in to where you have seen this? @michalk-k As far as I am aware, HA does not keep a blacklist of custom components. HACS does, but LTSS is not on it.

**Comment by freol35241** [comment]
Closed with the release of [v2.1.1](https://github.com/freol35241/ltss/releases/tag/v2.1.1)

**Comment by st-schuler** [comment]
> @st-schuler Please try out [v2.1.1-alpha](https://github.com/freol35241/ltss/releases/tag/v2.1.1-alpha). It should fix this error.
> 
> And for the blacklist, can you please point me in to where you have seen this? @michalk-k As far as I am aware, HA does not keep a blacklist of custom components. HACS does, but LTSS is not on it.

Sorry for the late response. It works now. Thanks!

**Comment by michalk-k** [comment]
> @st-schuler Please try out [v2.1.1-alpha](https://github.com/freol35241/ltss/releases/tag/v2.1.1-alpha). It should fix this error.
> 
> And for the blacklist, can you please point me in to where you have seen this? @michalk-k As far as I am aware, HA does not keep a blacklist of custom components. HACS does, but LTSS is not on it.

Sorry for late answer.
TBH I don't know. I had been requested to report it to ha-core what I've done. Then one of my colleagues informed me, that HACS  refused to install ltss. But is a HA newcomer it's hard to collect more details. Maybe it prevents installation only (not running)

BTW thanks for fixing ltss
with regards.
