### ISSUE TITLE
Geoalchemy2 error

### ISSUE THREAD

**Issue by ciberkids** [freol35241/ltss#234]
I have used ltss for the past 6 month and it has always worked fine.
It got updated last week and not i got this error 

```
2024-12-07 23:36:12.516 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration 'ltss': Unable to import component: No module named 'geoalchemy2'

Traceback (most recent call last):

  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component

    component = await integration.async_get_component()

                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1034, in async_get_component

    self._component_future.result()

    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1014, in async_get_component

    comp = await self.hass.async_add_import_executor_job(

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

        self._get_component, True

        ^^^^^^^^^^^^^^^^^^^^^^^^^

    )

    ^

  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run

    result = self.fn(*self.args, **self.kwargs)

  File "/usr/src/homeassistant/homeassistant/loader.py", line 1074, in _get_component

    ComponentProtocol, importlib.import_module(self.pkg_path)

                       ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^

  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func

    return func(*args, **kwargs)

  File "/usr/local/lib/python3.13/importlib/__init__.py", line 88, in import_module

    return _bootstrap._gcd_import(name[level:], package, level)

           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 1022, in exec_module

  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed

  File "/config/custom_components/ltss/__init__.py", line 42, in <module>

    from .models import Base, LTSS

  File "/config/custom_components/ltss/models.py", line 16, in <module>

    from geoalchemy2 import Geometry

ModuleNotFoundError: No module named 'geoalchemy2'
```

i see the problem is with the module `geoalchemy2` can some one help me to understand what is wrong?

thanks a lot

**Comment by freol35241** [comment]
@ciberkids on what hardware is this? LTSS is tested on all new releases of HA and I cannot seem to reproduce this error.

**Comment by matteohexagon** [comment]
Hi, thanks for you answer,

I am running HA in a container, run by podman.

i cannot tell what has updated, i would say HomeAssistant, now it is at this version:
```
Core 2024.12.3
Frontend 20241127.8
```
i have double checked and in the docker image from home assistant there ISN'T that `geoalchemy` package and if i install it manually with `pip` then it starts working as intended, problem is that  as soon as the machine reboots for normal maintenance and thus the container, then i have to redo everything manually :(

i forgot to mention that that logs is reported by HomeAssistant at its startup

**Comment by dgsardina** [comment]
Just having this issue on LTSS v2.1.1 on HACS. geoalchemy2 is missing. Doing pip install geoalchemy2 fixes it until the container is regenerated.

**Comment by andreala** [comment]
Same effects here 
2024.12.3 and 20241127.8.
